services:
  postgres:
    image: postgres:15-alpine
    container_name: exercio-db
    restart: always
    environment:
      POSTGRES_USER: exercio
      POSTGRES_PASSWORD: exercio_secret_2026
      POSTGRES_DB: exercio_db
    ports:
      - "5432:5432"
    volumes:
      - exercio_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: exercio-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@exercio.app
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - postgres

volumes:
  exercio_postgres_data:
    name: exercio_postgres_data
