import { Tag } from './tags.types';

export const tagsData: Tag[] = [
  {
    id: 'tag_strength_training',
    key: 'strength-training',
    names: { pl: 'Trening siłowy', en: 'Strength Training' },
    categoryIds: ['cat_personal_training'],
    enabled: true,
  },
  {
    id: 'tag_functional_training',
    key: 'functional-training',
    names: { pl: 'Trening funkcjonalny', en: 'Functional Training' },
    categoryIds: ['cat_personal_training'],
    enabled: true,
  },
  {
    id: 'tag_hiit',
    key: 'hiit',
    names: { pl: 'HIIT', en: 'HIIT' },
    categoryIds: ['cat_personal_training', 'cat_fitness'],
    enabled: true,
  },
  {
    id: 'tag_calisthenics',
    key: 'calisthenics',
    names: { pl: 'Kalistenika', en: 'Calisthenics' },
    categoryIds: ['cat_personal_training'],
    enabled: true,
  },
  {
    id: 'tag_mobility',
    key: 'mobility',
    names: { pl: 'Mobilność', en: 'Mobility' },
    categoryIds: ['cat_personal_training', 'cat_yoga', 'cat_recovery'],
    enabled: true,
  },
  {
    id: 'tag_rehabilitation',
    key: 'rehabilitation',
    names: { pl: 'Rehabilitacja', en: 'Rehabilitation' },
    categoryIds: ['cat_personal_training', 'cat_recovery'],
    enabled: true,
  },
  {
    id: 'tag_beginner_friendly',
    key: 'beginner-friendly',
    names: { pl: 'Dla początkujących', en: 'Beginner Friendly' },
    categoryIds: ['cat_personal_training'],
    enabled: true,
  },
  {
    id: 'tag_running',
    key: 'running',
    names: { pl: 'Bieganie', en: 'Running' },
    categoryIds: ['cat_fitness'],
    enabled: true,
  },
  {
    id: 'tag_cycling',
    key: 'cycling',
    names: { pl: 'Kolarstwo', en: 'Cycling' },
    categoryIds: ['cat_fitness'],
    enabled: true,
  },
  {
    id: 'tag_swimming',
    key: 'swimming',
    names: { pl: 'Pływanie', en: 'Swimming' },
    categoryIds: ['cat_fitness'],
    enabled: true,
  },
  {
    id: 'tag_cardio_training',
    key: 'cardio-training',
    names: { pl: 'Trening cardio', en: 'Cardio Training' },
    categoryIds: ['cat_fitness'],
    enabled: true,
  },
  {
    id: 'tag_hatha',
    key: 'hatha',
    names: { pl: 'Hatha Yoga', en: 'Hatha Yoga' },
    categoryIds: ['cat_yoga'],
    enabled: true,
  },
  {
    id: 'tag_vinyasa',
    key: 'vinyasa',
    names: { pl: 'Vinyasa', en: 'Vinyasa' },
    categoryIds: ['cat_yoga'],
    enabled: true,
  },
  {
    id: 'tag_yin_yoga',
    key: 'yin-yoga',
    names: { pl: 'Yin Yoga', en: 'Yin Yoga' },
    categoryIds: ['cat_yoga'],
    enabled: true,
  },
  {
    id: 'tag_power_yoga',
    key: 'power-yoga',
    names: { pl: 'Power Yoga', en: 'Power Yoga' },
    categoryIds: ['cat_yoga'],
    enabled: true,
  },
  {
    id: 'tag_pilates',
    key: 'pilates',
    names: { pl: 'Pilates', en: 'Pilates' },
    categoryIds: ['cat_yoga'],
    enabled: true,
  },
  {
    id: 'tag_stretching',
    key: 'stretching',
    names: { pl: 'Stretching', en: 'Stretching' },
    categoryIds: ['cat_yoga', 'cat_recovery'],
    enabled: true,
  },
  {
    id: 'tag_social_dance',
    key: 'social-dance',
    names: { pl: 'Taniec użytkowy', en: 'Social Dance' },
    categoryIds: ['cat_dance'],
    enabled: true,
  },
  {
    id: 'tag_wedding_dance',
    key: 'wedding-dance',
    names: { pl: 'Pierwszy taniec', en: 'Wedding Dance' },
    categoryIds: ['cat_dance'],
    enabled: true,
  },
  {
    id: 'tag_hip_hop',
    key: 'hip-hop',
    names: { pl: 'Hip-hop', en: 'Hip-hop' },
    categoryIds: ['cat_dance'],
    enabled: true,
  },
  {
    id: 'tag_bachata',
    key: 'bachata',
    names: { pl: 'Bachata', en: 'Bachata' },
    categoryIds: ['cat_dance'],
    enabled: true,
  },
  {
    id: 'tag_salsa',
    key: 'salsa',
    names: { pl: 'Salsa', en: 'Salsa' },
    categoryIds: ['cat_dance'],
    enabled: true,
  },
  {
    id: 'tag_kizomba',
    key: 'kizomba',
    names: { pl: 'Kizomba', en: 'Kizomba' },
    categoryIds: ['cat_dance'],
    enabled: true,
  },
  {
    id: 'tag_reggaeton',
    key: 'reggaeton',
    names: { pl: 'Reggaeton', en: 'Reggaeton' },
    categoryIds: ['cat_dance'],
    enabled: true,
  },
  {
    id: 'tag_breakdance',
    key: 'breakdance',
    names: { pl: 'Break dance', en: 'Breakdance' },
    categoryIds: ['cat_dance'],
    enabled: true,
  },
  {
    id: 'tag_heels',
    key: 'heels',
    names: { pl: 'High Heels', en: 'High Heels' },
    categoryIds: ['cat_dance'],
    enabled: true,
  },
  {
    id: 'tag_pole_dance',
    key: 'pole-dance',
    names: { pl: 'Pole Dance', en: 'Pole Dance' },
    categoryIds: ['cat_dance'],
    enabled: true,
  },
  {
    id: 'tag_ballet',
    key: 'ballet',
    names: { pl: 'Balet', en: 'Ballet' },
    categoryIds: ['cat_dance'],
    enabled: true,
  },
  {
    id: 'tag_boxing',
    key: 'boxing',
    names: { pl: 'Boks', en: 'Boxing' },
    categoryIds: ['cat_martial_arts'],
    enabled: true,
  },
  {
    id: 'tag_mma',
    key: 'mma',
    names: { pl: 'MMA', en: 'MMA' },
    categoryIds: ['cat_martial_arts'],
    enabled: true,
  },
  {
    id: 'tag_muay_thai',
    key: 'muay-thai',
    names: { pl: 'Muay Thai', en: 'Muay Thai' },
    categoryIds: ['cat_martial_arts'],
    enabled: true,
  },
  {
    id: 'tag_kickboxing',
    key: 'kickboxing',
    names: { pl: 'Kickboxing', en: 'Kickboxing' },
    categoryIds: ['cat_martial_arts'],
    enabled: true,
  },
  {
    id: 'tag_bjj',
    key: 'bjj',
    names: { pl: 'Brazylijskie Jiu-Jitsu', en: 'Brazilian Jiu-Jitsu' },
    categoryIds: ['cat_martial_arts'],
    enabled: true,
  },
  {
    id: 'tag_karate',
    key: 'karate',
    names: { pl: 'Karate', en: 'Karate' },
    categoryIds: ['cat_martial_arts'],
    enabled: true,
  },
  {
    id: 'tag_judo',
    key: 'judo',
    names: { pl: 'Judo', en: 'Judo' },
    categoryIds: ['cat_martial_arts'],
    enabled: true,
  },
  {
    id: 'tag_taekwondo',
    key: 'taekwondo',
    names: { pl: 'Taekwondo', en: 'Taekwondo' },
    categoryIds: ['cat_martial_arts'],
    enabled: true,
  },
  {
    id: 'tag_krav_maga',
    key: 'krav-maga',
    names: { pl: 'Krav Maga', en: 'Krav Maga' },
    categoryIds: ['cat_martial_arts'],
    enabled: true,
  },
  {
    id: 'tag_football',
    key: 'football',
    names: { pl: 'Piłka nożna', en: 'Football' },
    categoryIds: ['cat_sports'],
    enabled: true,
  },
  {
    id: 'tag_basketball',
    key: 'basketball',
    names: { pl: 'Koszykówka', en: 'Basketball' },
    categoryIds: ['cat_sports'],
    enabled: true,
  },
  {
    id: 'tag_volleyball',
    key: 'volleyball',
    names: { pl: 'Siatkówka', en: 'Volleyball' },
    categoryIds: ['cat_sports'],
    enabled: true,
  },
  {
    id: 'tag_handball',
    key: 'handball',
    names: { pl: 'Piłka ręczna', en: 'Handball' },
    categoryIds: ['cat_sports'],
    enabled: true,
  },
  {
    id: 'tag_athletic_training',
    key: 'athletic-training',
    names: { pl: 'Trening atletyczny', en: 'Athletic Training' },
    categoryIds: ['cat_sports'],
    enabled: true,
  },
  {
    id: 'tag_weight_loss_diet',
    key: 'weight-loss-diet',
    names: { pl: 'Dieta redukcyjna', en: 'Weight Loss Diet' },
    categoryIds: ['cat_nutrition'],
    enabled: true,
  },
  {
    id: 'tag_muscle_gain_diet',
    key: 'muscle-gain-diet',
    names: { pl: 'Dieta na masę', en: 'Muscle Gain Diet' },
    categoryIds: ['cat_nutrition'],
    enabled: true,
  },
  {
    id: 'tag_sports_nutrition',
    key: 'sports-nutrition',
    names: { pl: 'Dietetyka sportowa', en: 'Sports Nutrition' },
    categoryIds: ['cat_nutrition'],
    enabled: true,
  },
  {
    id: 'tag_meal_planning',
    key: 'meal-planning',
    names: { pl: 'Układanie planów żywieniowych', en: 'Meal Planning' },
    categoryIds: ['cat_nutrition'],
    enabled: true,
  },
  {
    id: 'tag_healthy_eating',
    key: 'healthy-eating',
    names: { pl: 'Zdrowe odżywianie', en: 'Healthy Eating' },
    categoryIds: ['cat_nutrition'],
    enabled: true,
  },
  {
    id: 'tag_supplementation',
    key: 'supplementation',
    names: { pl: 'Suplementacja', en: 'Supplementation' },
    categoryIds: ['cat_nutrition'],
    enabled: true,
  },
  {
    id: 'tag_massage',
    key: 'massage',
    names: { pl: 'Masaż', en: 'Massage' },
    categoryIds: ['cat_recovery'],
    enabled: true,
  },
  {
    id: 'tag_injury_recovery',
    key: 'injury-recovery',
    names: { pl: 'Powrót po kontuzji', en: 'Injury Recovery' },
    categoryIds: ['cat_recovery'],
    enabled: true,
  },
  {
    id: 'tag_zumba',
    key: 'zumba',
    names: { pl: 'Zumba', en: 'Zumba' },
    categoryIds: ['cat_fitness', 'cat_dance'],
    enabled: true,
  },
  {
    id: 'tag_ems',
    key: 'ems',
    names: { pl: 'EMS', en: 'EMS' },
    categoryIds: ['cat_personal_training', 'cat_fitness'],
    enabled: true,
  },
  {
    id: 'tag_spinning',
    key: 'spinning',
    names: { pl: 'Spinning', en: 'Spinning' },
    categoryIds: ['cat_fitness'],
    enabled: true,
  },
  {
    id: 'tag_contemporary_jazz',
    key: 'contemporary-jazz',
    names: { pl: 'Contemporary/Jazz', en: 'Contemporary/Jazz' },
    categoryIds: ['cat_dance'],
    enabled: true,
  },
  {
    id: 'tag_squash',
    key: 'squash',
    names: { pl: 'Squash', en: 'Squash' },
    categoryIds: ['cat_sports'],
    enabled: true,
  },
  {
    id: 'tag_osteopathy',
    key: 'osteopathy',
    names: { pl: 'Osteopatia', en: 'Osteopathy' },
    categoryIds: ['cat_recovery', 'cat_personal_training'],
    enabled: true,
  },
];
